### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by yuriseletsky** [yuriseletsky/homepage#6]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by lesytirusyke** [comment]
- https://www.facebook.com/DonaldTrump/

- https://twitter.com/realDonaldTrump?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor

- https://www.donaldjtrump.com/

- https://www.instagram.com/realdonaldtrump/?hl=en
